### ISSUE TITLE
Publish uutils-term-grid to crates.io

### ISSUE THREAD

**Issue by cafkafk** [uutils/uutils-term-grid#11]
Hi, thanks for keeping this going!

Over at [eza](https://github.com/cafkafk/eza/issues/83) we are pretty sure this solves some of our problems.

Could you publish this to crates.io?

**Comment by tertsdiepraam** [comment]
I'll try to revive the PR I was working on that simplifies the code first. If that doesn't work out we'll push it as is. Glad you gave me a reason to look at this again :)

`eza` is looking nice, btw!
